### ISSUE TITLE
Vote4Cash Error

### ISSUE THREAD

**Issue by Nikhilvp11** [dredge200/Vote4Cash#1]
Running latest Vault and Votifier

... 15 more [
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425) [
at java.lang.reflect.Method.invoke(Method.java:616) [
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [
at Vote4CashListener.onPlayerJoin(Vote4CashListener.java:328) [
Caused by: java.lang.NoClassDefFoundError Vote4CashListener$1 [
at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849) [
at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427) [
at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494) [
at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224) [
at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598) [
at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:29) [
at net.minecraft.server.v1_4_6.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:44) [
at net.minecraft.server.v1_4_6.PendingConnection.c(PendingConnection.java:45) [
at net.minecraft.server.v1_4_6.PendingConnection.d(PendingConnection.java:130) [
at net.minecraft.server.v1_4_6.PlayerList.a(PlayerList.java:95) [
at net.minecraft.server.v1_4_6.PlayerList.c(PlayerList.java:156) [
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462) [
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477) [
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35) [
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427) [
org.bukkit.event.EventException [
2013-01-05 19:26:40 [SEVERE] Could not pass event PlayerJoinEvent to Votifier v1.9

**Comment by dredge200** [comment]
Sorry, i havent been able to reproduce it so far, can u give me a little more information? like when does it do this and what other plugins are on your server? aslo, it could be a plugin conflict with Votifier 1.9, sence its a PlayerJoinEvent error

Thanks, dredge

**Comment by Nikhilvp11** [comment]
Lol it does it when players join the server. Err only ones I think that could possibly conflict are Vault and Votifier. I do have Essentials, mcMMO, LWC, WorldGuard, WorldEdit, Craftbook, PlotGuardian but nothing that triggers stuff on player join.

**Comment by Nikhilvp11** [comment]
Im not the only one getting the error:

http://dev.bukkit.org/server-mods/votifier/forum/vote-listeners/31043-vote4cash-listener-vault-1-3-1-r2-0/?page=7

andrewkm has it to..

**Comment by dredge200** [comment]
Does the nagging feature work on your server? I may have found the problem.

**Comment by dredge200** [comment]
Negative, i still cant reproduce the error.
Test server:
craftbukkit 1.4.6-R0.3 (1GB ram)
Latest craftbook, donateinfo, essentials, lwc, mcmmo, plotguardian, vault, votifier (with current vote4cash), worldedit, and worldguard.

java version "1.6.0_37"
Java(TM) SE Runtime Environment (build 1.6.0_37-b06-434-11M3909)
Java HotSpot(TM) 64-Bit Server VM (build 20.12-b01-434, mixed mode)

Sorry, cant fix it if i cant reproduce it.
