### ISSUE TITLE
Vote4Cash Could not pass event PlayerJoinEvent to Votifier v1.9

### ISSUE THREAD

**Issue by Nikhilvp11** [dredge200/Vote4Cash#2]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425) [
at java.lang.reflect.Method.invoke(Method.java:616) [
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [
at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source) [
at Vote4CashListener.onPlayerJoin(Vote4CashListener.java:328) [
Caused by: java.lang.NoClassDefFoundError: Vote4CashListener$1 [
at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849) [
at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427) [
at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494) [
at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224) [
at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598) [
at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:29) [
at net.minecraft.server.v1_4_R1.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:44) [
at net.minecraft.server.v1_4_R1.PendingConnection.c(PendingConnection.java:45) [
at net.minecraft.server.v1_4_R1.PendingConnection.d(PendingConnection.java:130) [
at net.minecraft.server.v1_4_R1.PlayerList.a(PlayerList.java:95) [
at net.minecraft.server.v1_4_R1.PlayerList.c(PlayerList.java:156) [
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462) [
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477) [
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35) [
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427) [
org.bukkit.event.EventException [
2013-02-06 21:01:42 [SEVERE] Could not pass event PlayerJoinEvent to Votifier v1.9

Same issue as before but I think I've noticed the problem I THINK. its when someone joins  that hasnt voted. I tested it when I voted and console outputted correct information but I saw when someone hadnt voted the error appears?

**Comment by Nikhilvp11** [comment]
This time I'm running 1.4.7-R0.1 though!

**Comment by dredge200** [comment]
Ok, try also downloading the Vote4CashListener$1.class file and placing it in the same directory as the other one
Link: https://github.com/dredge200/Vote4Cash/blob/master/bin/Vote4CashListener%241.class
Click the "raw" button to download.

If this works, or not, please come back and tell me.

**Comment by Nikhilvp11** [comment]
Placed it in the folder with it:

[WARNING] [Votifier] Error loading 'Vote4CashListener$1' listener! Listener disabled.

But Vote4CashListener runs fine. It's weird sometimes the error above appears and sometimes It dosen't, it's really hard to pinpoint what's causing it.....

**Comment by dredge200** [comment]
Yeah, i couldn't reproduce it at all, but if that solved the problem, thats good.
